/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  kotlin("jvm") version "2.3.0"
  application
}

group = "org.example" // A company name, for example, `org.jetbrains`
version = "1.0-SNAPSHOT" // Version to assign to the built artifact

repositories { // Sources of dependencies. See 
    mavenCentral() // Maven Central Repository. See 
}

dependencies { // All the libraries you want to use. See 
    // Copy dependencies' names after you find them in a repository
    testImplementation(kotlin("test")) // The Kotlin test library
}

tasks.test { // See 
    useJUnitPlatform() // JUnitPlatform for tests. See 
}

application {
    mainClass.set("MainKt")
}
