/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  alias(libs.plugins.kotlinMultiplatform)
  alias(libs.plugins.kotlinxSerialization)
  // kotlin("jvm") version "2.3.0"
  // application
}

// group = "org.example" // A company name, for example, `org.jetbrains`
// version = "1.0-SNAPSHOT" // Version to assign to the built artifact

repositories { // Sources of dependencies. See 
    mavenCentral() // Maven Central Repository. See 
}

// dependencies { // All the libraries you want to use. See 
//     // Copy dependencies' names after you find them in a repository
//     testImplementation(kotlin("test")) // The Kotlin test library
// }
// 
// tasks.test { // See 
//     useJUnitPlatform() // JUnitPlatform for tests. See 
// }
// 
// application {
//     mainClass.set("MainKt")
// }


kotlin {
    val hostOs = System.getProperty("os.name")
    val isArm64 = System.getProperty("os.arch") == "aarch64"
    val isMingwX64 = hostOs.startsWith("Windows")
    val nativeTarget = when {
        hostOs == "Mac OS X" && isArm64 -> macosArm64("native")
        hostOs == "Mac OS X" && !isArm64 -> macosX64("native")
        hostOs == "Linux" && isArm64 -> linuxArm64("native")
        hostOs == "Linux" && !isArm64 -> linuxX64("native")
        isMingwX64 -> mingwX64("native")
        else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
    }

    nativeTarget.apply {
        binaries {
            executable {
                entryPoint = "main"
            }
        }
    }

    targets.withType<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget> {
        binaries.all {
            freeCompilerArgs += "-g"
            linkerOpts("-g")
        }
    }

    sourceSets {
        nativeMain.dependencies {
            implementation(libs.kotlinxSerializationJson)
            implementation(libs.okio)
        }
    }
}


tasks.register<Exec>("shell") {
  group = "custom"
  executable = "/bin/bash"
  args("-c", "echo i waws here")
}
